version: '3.8'
services:
  mongodb:
    image: mongo:7.0
    container_name: mongo_db
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo_data: